name: pubx
description: The missing pub commands. Search and view packages from pub.dev
  from the command line.
version: 1.1.0
authors:
  - Scott Hyndman <scotty.hyndman@gmail.com>
  - Gon√ßalo Palma <solid.goncalo@gmail.com>
homepage: https://github.com/shyndman/pubx
repository: https://github.com/shyndman/pubx

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  pubx:

dependencies:
  args: ^1.5.0
  http: ^0.12.0
  path: ^1.6.0
  yaml: ^2.1.16

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
